# Generated by Django 5.2.11 on 2026-02-08 08:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autograder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=100, unique=True)),
                ('question_text', models.TextField()),
                ('expected_keywords', models.TextField(help_text='Comma-separated keywords')),
                ('model_answer', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='studentanswer',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='matched_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='missing_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='question_id_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='extracted_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='student_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_answers/'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autograder.teacherquestion'),
        ),
    ]
