# Generated by Django 5.2.11 on 2026-02-08 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autograder', '0002_teacherquestion_alter_studentanswer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherquestion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Teacher Question', 'verbose_name_plural': 'Teacher Questions'},
        ),
    ]
